### ISSUE TITLE
Error on deserialization server response

### ISSUE THREAD

**Issue by MihailRomanov** [Franklin89/NGitLab#21]
Hello!
I try to read tree in project repository.

I use follow code:
```
var projects = client.Projects.Accessible;
var repository = client.GetRepository(projects.First().Id);
var a = repository.Tree.ToList();
```

I receive exception:
```
System.InvalidCastException: Invalid cast from 'System.String' to 'NGitLab.Models.ObjectType'.
Result StackTrace:	
at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at NGitLab.Impl.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at NGitLab.Impl.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at NGitLab.Impl.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type)
   at NGitLab.Impl.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy)
   at NGitLab.Impl.SimpleJson.DeserializeObject[T](String json)
   at NGitLab.Impl.HttpRequestor.Enumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ThridPartyLibrariesInvestigations.NGitLabTests.GetFileList()
```
I use Fiddler for intercept response from server, and I get Json:
```
[{"id":"b392431d25edf7fe8f86233e0fb6c24c6968b6c0","name":"Maksim_Kirshin","type":"tree","mode":"040000"},{"id":"73373e62972ef6d8bde2732f9b941455c6dd72ca","name":"Pavel_Mihailov","type":"tree","mode":"040000"}]
```

Could you help me?

**Comment by MihailRomanov** [comment]
How I understand it's old problem - SimpleJson do not support enum serialization (see https://github.com/facebook-csharp-sdk/simple-json/issues/15).

I see 2 variants:
- apply some path to SimpleJson in NGitLab project (how I understand - now SimpleJson library is not supported, and don't receive pull requests).
- use other Json serializer (.Net internal, Json.Net, ...)

What do you think?

**Comment by Scooletz** [comment]
Thank you for such a detailed description. I'll check it during forthcoming
weekend.
Which version of GitLab do you run?
24 cze 2015 18:06 "MihailRomanov" <notifications@github.com> napisał(a):

**Comment by MihailRomanov** [comment]
I haven't access to GitLab server and can't see version.
And I haven't found version in Web UI.

**Comment by Scooletz** [comment]
The internal patch in NGitLab is the way to go.
25 cze 2015 07:59 "MihailRomanov" <notifications@github.com> napisał(a):
